### ISSUE TITLE
What should I do if I need to use metrics and logging services in the application layer?

### ISSUE THREAD

**Issue by budarin** [bespoyasov/frontend-clean-architecture#13]

**Comment by bespoyasov** [comment]
For composing cross-cutting concerns, [I'd recommend decorators](https://bespoyasov.me/blog/explicit-design-7/).

If, for any reason, it doesn't work for you, there's always an option to just declare those services in the dependencies and “inject” and use them as other dependencies.

**Comment by budarin** [comment]
Alex, most issues are questions on the concept so you should add discussions to the project and convert such issues to discussions.

This will help other developers in learning and will allow you not to create repetitive questions.

**Comment by budarin** [comment]
Decorators are good only when it is necessary to perform an action around the entire method, but what about the situation when I need to call the service in several places in the application layer method?

It turns out that we can't directly call application layer methods after injecting services into them in one way or another - where to place newly created entities and how to beat developers' hands so that when they see the domain, application, etc. folders, they don't go there, they go somewhere for layers already enriched with services?
