### ISSUE TITLE
Isn't it superfluous to export functions in adapters instead of constants?

### ISSUE THREAD

**Issue by budarin** [bespoyasov/frontend-clean-architecture#15]
```ts
import { NotificationService } from "../application/ports";

export function useNotifier(): NotificationService {
  return {
    notify: (message: string) => window.alert(message),
  };
}
```
vs
```ts
import { NotificationService } from "../application/ports";

export const notifier: NotificationService = { 
  notify: (message: string) => window.alert(message) 
}
```

Calling functions that return a new service object each time leads to an overhead during code execution and also generates a bunch of garbage for GC.  This is practically nothing - for the client, but if such code is used in SSR, this is already a problem

**Comment by bespoyasov** [comment]
It is an implementation detail; the concept from the post forces no constraints on how to do it.

The example in the text uses Hooks as “poor man's DI” and, for consistency, uses it when exposing adapters, too.

**Comment by budarin** [comment]
in this case, doesn't the module itself act like a homemade DI? 😊

**Comment by bespoyasov** [comment]
If, in testing, there are no preferences or constraints on mocking a module versus injecting a stub as a dependency, it might.
